function [image_points_left,...
          image_points_right]=calculation_matched_points(image_left,...
                                                         image_right,...
                                                         list_index)

%detect checkerboards in images
image_points_left=calculation_image_points(image_left,list_index);
image_points_right=calculation_image_points(image_right,list_index);

%unvoid output
if size(image_points_left,1)~=0&&size(image_points_right,1)~=0

    % Visualize candidate matches
    figure;
    showMatchedFeatures(image_left,...
                        image_right,...
                        image_points_left,...
                        image_points_right,...
                        'montage');
    title('Feature Points Matching (original image)')
    
end
